### ISSUE TITLE
Minor tweaks & features pre-T7

### ISSUE THREAD

**Issue by Sebastien32** [rvazarkar/NGUInjector#10]
- Add CAPAUG functionality, rather than AUG-X, should function identically to CAPTM. As augs become very cheap, its impractical to use the AUG-X syntax in any meaningful way.

- Add Blood Magic cutoffs for rituals to stop at certain values, i.e. stop casting DC at 40% bonus

- Add an option to manual minor quests in addition to just manualling majors (later game players will use this).

Take time to yourself and don't be too pressured!

**Comment by rvazarkar** [comment]
All done.
