### ISSUE TITLE
Add 'BLANK' E/M allocation to allow leaving energy unallocated

### ISSUE THREAD

**Issue by Sebastien32** [rvazarkar/NGUInjector#11]
I.e. if you wanted to spend 1/2 of your energy on augs after capping tm, you could do:

"CAPTM", "AUG-9", "AUG-10", "BLANK", "BLANK"

**Comment by Sebastien32** [comment]
Allows for holding unallocated resources for t8 feature

**Comment by rvazarkar** [comment]
https://github.com/rvazarkar/NGUInjector/commit/7dd676ab004b51d6979f15fb2ab91cc1ce9a123f

Added here
