### ISSUE TITLE
Suggestion: Auto-buy diggers

### ISSUE THREAD

**Issue by developingedan** [rvazarkar/NGUInjector#15]
settings:
{
  "_autobuyDiggersPriority": [
    0, ..., 11
  ],
  "_autobuyDiggersBalance": true,
  "_autobuyDiggersLeaveMoneypitThreshold": true,
  ...
}
_autobuyDiggersPriority - array of digger offsets to autobuy
_autobuyDiggersBalance - keep digger levels (based on priority) the same
_autobuyDiggersLeaveMoneypitThreshold - leave enough money to maintain money pit threshold

**Comment by yoksi** [comment]
it is solved in v3.1.0, if I may say :D

**Comment by developingedan** [comment]
<3
