### ISSUE TITLE
Problems with "Use Gold Loadout"

### ISSUE THREAD

**Issue by orcuttk** [rvazarkar/NGUInjector#19]
Initial Gold Zone on rebirth as of 2.6.0 does not use Gold Loadout.

Also, "Use Gold Loadout" checkbox in "Gold" section unchecks every time the menu is opened and needs to be rechecked.

**Comment by yoksi** [comment]
Initial Gold Zone - Automation will visit this zone to kill an enemy to jumpstart your time machine initially.
= not using loadout (maybe not needed if you using "Allow Fallthrough")

Use Gold Loadout - If checked, automation will go to the target zone and snipe a boss in gold loadout gear. This will automatically enable itself on each rebirth.
= quick snipe BOSS and automatically shuts off

**Comment by rvazarkar** [comment]
Fixed in 3.0
