### ISSUE TITLE
Can't Open Settings

### ISSUE THREAD

**Issue by OJofSteel** [rvazarkar/NGUInjector#2]
Since i don't have a numpad, i can't open the settings page. Perhaps something in settings to change menu keybind?

**Comment by helldragger** [comment]
Same problem here

**Comment by rvazarkar** [comment]
Fixed in https://github.com/rvazarkar/NGUInjector/commit/d66207fa299c07e3c300fbfae1e69130e6f8c359. 

New version will use F1-F4 instead of numpad, hopefully theres no conflicts
