### ISSUE TITLE
Suggestion: Allow Fallthrough for GOLD

### ISSUE THREAD

**Issue by yoksi** [rvazarkar/NGUInjector#20]
Hello, maybe good idea for even better automatization for player which are not so far in NGU.

=Adding option for something like "Allow Fallthrough" for GOLD.
This option automatically snipe first BOSS in every new zone (highest zone) with gold loadout.

I believe its very useful if you playing from start for example Challenges purposes.

**Comment by ingwarsw** [comment]
I think it was resolved by #22
