### ISSUE TITLE
Suggestion: auto rebirths based on the Number aka FastForward

### ISSUE THREAD

**Issue by yoksi** [rvazarkar/NGUInjector#32]
What about add option for auto rebirth which are not based on specific time, but when the NUMBER is higher (12.100E6 > 12.100E9) than the previous one from last rebirth. (customizable minimal multiplier?)

Fixed rebirth time is OK for harvesting EXP in one place, but for fully unattended play you need something more "maintenance-free".

**Comment by rvazarkar** [comment]
Done in https://github.com/rvazarkar/NGUInjector/commit/9e2c1aff329ce2f1e844040683904ba095fcd1be
