### ISSUE TITLE
Suggestion: Take uncertainty out of gold generation

### ISSUE THREAD

**Issue by trulypoison** [rvazarkar/NGUInjector#33]
Something i noticed while working on cblock - There's a random amount of time that can pass between rebirthing and your time machine starting while you sit and wait for a boss to spawn in a zone to snipe. I suggest changing it to after rebirth switching to highest zone available, killing 1 creature and then sniping a boss so at the very least you have money generating in the TM while you wait for optimal gold generation.

Idea of how to implement:
on rebirth if you have TM unlocked - move to highest available zone, and let it fight whatever spawns. Then during the next 10 second cycle you switch to sniping for a boss with gold loadout

**Comment by yoksi** [comment]
this option was removed from 3.0, but if you making fast rebirths, then waiting for first boss (which can take more than 60 seconds) is a problem...

snipe first passersby and immediately after that search for boss

**Comment by trulypoison** [comment]
You could make it a setting that only applies when "Cblock mode" is selected I guess. Since that is when it'll consistently search a new zone to snipe it.

**Comment by rvazarkar** [comment]
In 3.1, the script will first hit Tutorial Zone for initial gold with bossonly off and then your gold zone immediately after
