### ISSUE TITLE
Suggestion: tweaks

### ISSUE THREAD

**Issue by yoksi** [rvazarkar/NGUInjector#34]
- if you turn off master switch and forget to change combat from manual to idle =stuck with no progress and eventually you get killed
- top left overlay injector info could display which allocation profile is currently active (useful if injector is hidden)
plus maybe adding shadow to font for better readability

**Comment by rvazarkar** [comment]
If you turn off master switch, it turns everything off. That's the intended behavior. Unfortunately, very limited in what I can do with a unity label, so no way to add a drop shadow as far as I know
