### ISSUE TITLE
Suggestion: Adventure mode ITOPOD settings

### ISSUE THREAD

**Issue by cdmichaelb** [rvazarkar/NGUInjector#39]
![](https://i.imgur.com/TrkXvTP.png)

A second set of options to differentiate between itopod fallthrough and main farm area.

For example in itopod it's pretty typical to have beast mode on, fast combat on, recover hp off, precast buff off.
But for titans you want precast buffs, recovery hp, fast combat off, beast mode off.
For sniping it's some variation depending how strong you are.

**Comment by rvazarkar** [comment]
Added in 3.1
