### ISSUE TITLE
better allocation setting edition

### ISSUE THREAD

**Issue by helldragger** [rvazarkar/NGUInjector#4]
Could be cool to be able to: 
- change the allocation settings in game
- be able to set the time using hours, minutes, seconds ex: "time" : { "h":1, "m":30 } or "time":"1h30m"
- set durations instead of time to start a step, so we can easily just create 1h of x, followed by 2h of Y..

**Comment by rvazarkar** [comment]
I'm going to reject this because it adds complexity both for coding as well as for documenting and explaining different formats. The current format works fine and its pretty easy to use once you get used to it with a few calculations
