### ISSUE TITLE
Suggestion: more flexible Loadout presets

### ISSUE THREAD

**Issue by yoksi** [rvazarkar/NGUInjector#44]
Wouldn't it be easier to use loadout presets directly from the game (which can be up to 10) than your own in several sections (titans, gold, ...) which need to be maintained and updated separate?
Next to each Titan can be empty field for the number which loadout to use. For example, I use for some Titans loadout based on Power and for another Drop, so in the end it's not so flexible and I must manually select loadout.

Second thing, I don't know about allocation file, but taking care of those piles of numbers for Gear sections is a pain.

thanks for consideration

**Comment by rvazarkar** [comment]
The loadout system is designed this way so you don't have to buy loadout slots. If you use in game loadouts you're effectively limiting early game players to 1 or 2 loadouts tops.

**Comment by yoksi** [comment]
but as it is now it also uses only two loadouts or not? one for Titans and second for Gold (and update them once for a while)

**Comment by rvazarkar** [comment]
Titans, Gold, Yggdrasil, Money Pit is 4.

**Comment by yoksi** [comment]
I thought you would have some use for "build-in" presets and even more in later game, but if this is better then... ok
