### ISSUE TITLE
Pause completing Major Quests (or manual minors) when adventure zone is set to a Titan and it's available

### ISSUE THREAD

**Issue by trulypoison** [rvazarkar/NGUInjector#45]
Having recently unlocked questing I noticed that it takes full precedent over the adventure zone, which is fine when you're not simultaneously trying to farm a Titan like The Beast. 

Perhaps add a setting (checkbox?) to the script that allows it to switch from quest collecting to fight available titan if adventure zone target is set to one of them.

**Comment by rvazarkar** [comment]
Done in https://github.com/rvazarkar/NGUInjector/commit/54e821543aeb03b6a712df63a95a920c94e20ee5
