### ISSUE TITLE
Ignore switch to titan if same titan is set as AK in settings

### ISSUE THREAD

**Issue by trulypoison** [rvazarkar/NGUInjector#52]
Sorry, just realized this is a  _very minor_ issue. If script has highest AK titan set to Beast, but is also set to adventure zone beast in the settings you don't really need to swap to fight it. Unsure if it'll swap when "ITOPOD" is checked, but i'll check that next time the beast spawns.

**Comment by rvazarkar** [comment]
You still want to swap because your gear can be drop chance stuff

**Comment by trulypoison** [comment]
Not suggesting you don't swap the gear, just to the adventure zone.

**Comment by rvazarkar** [comment]
Ah I see what you mean, will try and take that into account
