### ISSUE TITLE
Splitting priorities seems to leave a lot of leftover resources

### ISSUE THREAD

**Issue by Ricky54326** [rvazarkar/NGUInjector#53]
Hello,

I've been following the project and decided to give it a try. I'd love to help contribute once I learn more about it.

One issue I've noticed is that I tend to have lots of excess resources even when I am not fully capping, and the resource allocation is not even. For example, I have my priorities set to split between NGU-0 and NGU-1 for mNGUs: https://i.imgur.com/oEiqJv5.png
The split is off by 10% or so, almost all of which is available sitting idle: https://i.imgur.com/d9Zsu5e.png

Any idea what might be causing this and how to fix (or how I could fix)?

I have also tried the `CAPNGU-X` directives, and it seems to generally attempt to cap the first priority which makes sense.

Cheers

**Comment by rvazarkar** [comment]
There's no issue. You just don't have enough energy to get to the next BB breakpoint. Assigning more energy to either NGU wouldn't increase your speed so the script leaves it unallocated. Feel free to assign it somewhere else and get more gains

**Comment by Ricky54326** [comment]
Makes sense. Thanks!
