### ISSUE TITLE
Suggestion: Check current diggers before changing them for other features

### ISSUE THREAD

**Issue by trulypoison** [rvazarkar/NGUInjector#55]
Just had an instance where my diggers changed for one feature, then another, and then instead of reverting back to the saved digger list for the current breakpoint it reverted back to the first feature (in this case Yggdrisil). 

If the call to change diggers is for diggers that are already equipped, unequipping any extra diggers that may be running is pointless (unless it's to achieve a higher potential bonus i guess by freeing up other GPS consumption?)

**Comment by rvazarkar** [comment]
Fixed in https://github.com/rvazarkar/NGUInjector/commit/1d5a4c79c52e526fd6dd06b8c95e5df705e28c2c
