### ISSUE TITLE
Manage NGU / Manage Wandoos has an issue with swapping.

### ISSUE THREAD

**Issue by cdmichaelb** [rvazarkar/NGUInjector#56]
I've witnessed it once with NGU after rebirth, not swapping to the correct NGU. Now I've witnessed it again, at 500seconds, not swapping to the correct Wandoos OS. Simply resaving the allocations.json without editing anything makes it immediately update the ngu/wandoos os.

`"Wandoos": [
    {
        "Time": 0,
        "OS": 0
    },
    {
        "Time": 500,
        "OS": 1
    }
],`

`11/6/2020-4:05 PM (85351s): Loaded Custom Allocation from profile 'allocation'
7 Energy Breakpoints
15 Magic Breakpoints
2 R3 Breakpoints
5 Gear Breakpoints
17 Digger Breakpoints
2 Wandoos Breakpoints
4 NGU Difficulty Breakpoints
Rebirth at 3700 seconds`

Here is what happened ~500 seconds in log:

`11/6/2020-6:47 PM (430s): Buying 4 magic purchases
11/6/2020-6:48 PM (480s): Buying 4 magic purchases
11/6/2020-6:48 PM (490s): Boosts Needed to Green: 0 Power, 0 Toughness, 7519950 Special
11/6/2020-6:48 PM (490s): Last Minute: -640990. Average Per Minute: 292859. ETA: 26 minutes.
11/6/2020-6:48 PM (500s): Received New Gear: 138,101,447,244,263,248,256,448,271,270,218,249,446,194,164,268,259,267,262
11/6/2020-6:48 PM (500s): Finished equipping gear
11/6/2020-6:49 PM (520s): Buying 6 magic purchases
11/6/2020-6:49 PM (550s): Boosts Needed to Green: 0 Power, 0 Toughness, 7062180 Special
11/6/2020-6:49 PM (550s): Last Minute: -457770. Average Per Minute: 300489. ETA: 24 minutes.
11/6/2020-6:50 PM (570s): Buying 6 magic purchases`

I don't have a log from when NGU messed up, I seemed to "fix" it by adding redundancy, so it changes at 0 seconds and 1 second.

**Comment by developingedan** [comment]
I get something a lot similar with diggers

**Comment by cdmichaelb** [comment]
I haven't experienced this issue lately. I'm not sure if it was fixed by chance with other code, or because I moved my times that I switch by 10 seconds. (510 vs 500 for example)

**Comment by rvazarkar** [comment]
I cant recreate this, so until theres a consistent way to do it, I'm closing this issue
