### ISSUE TITLE
XP EM management

### ISSUE THREAD

**Issue by helldragger** [rvazarkar/NGUInjector#6]
A way to setup a ratio to auto buy Energy and Magic stats with available xp:

- Setup the ratio for each stat using the custom purchases (base game mechanic)
- Setup EM ratio in settings (i.e: 10E/1M)
- if enough XP, check if buying all custom purchases for energy / magic brings the stats ratio closer to expected EM Ratio:
  - if better ratio: buy energy/magic custom purchase
  - else if already at best ratio: buy cheapest of two

**Comment by rvazarkar** [comment]
I added xp spend for e/m. It uses the custom purchases in the exp shop. If magic is unlocked, it'll buy one of energy and one of magic until it cant afford both. Otherwise it'll just buy exp if magic is still locked. This will keep you in ratio with minimal configuration
