### ISSUE TITLE
Suggestion: quick edit profile button

### ISSUE THREAD

**Issue by yoksi** [rvazarkar/NGUInjector#60]
hi,
what about button(?) for quick editing active profile next to profile selection window
...not so important thing to do, but I think convenient for people who often tweaking allocations

**Comment by rvazarkar** [comment]
What should this button do?

**Comment by yoksi** [comment]
quick edit profile in default text editor under Windows? its just suggestion because I tweaking active allocation profile fairly often and traveling thru folder structure is slow :P
