### ISSUE TITLE
Bug?: Diggers are not reActivated in Troll Challenges

### ISSUE THREAD

**Issue by yoksi** [rvazarkar/NGUInjector#71]
Hi, I dont know if this is bug or not, but if for example Troll Challenge disable all Diggers, then they are not re-activated.
Without active Diggers Trolls Ch. are quite hard, please make activation status check for Diggers permanent.

thanks

**Comment by rvazarkar** [comment]
Fixed in https://github.com/rvazarkar/NGUInjector/commit/ab1ee9e4e3b0fa517a2d272c21e958421bd368f9
