### ISSUE TITLE
Boost Recycling does not work with auto-recycle off

### ISSUE THREAD

**Issue by benway7000** [rvazarkar/NGUInjector#72]
Boost recycling does not seem to work when Manage Inventory is enabled. 

First I expected to see the lower-tier boost appear in the inventory to be managed on the next pass.  This never happens.

Then I watched the values of my items that were next in line to be boosted, and I never see the value go up by more than the original boost item - that is, it's not applying recycled boosts instantaneously.

I have 60% boost recycling. When I disable Inventory Management and manually boost, I get recycled boosts fairly often.

**Comment by cdmichaelb** [comment]
I think this is a misunderstanding of how boost recycling works. As soon here, it seems to be working as you describe it should.
https://i.imgur.com/wuMxRvH.mp4 that is with the auto-recycle turned off, so you actually see the boosts returned. https://i.imgur.com/q1mDoXj.png

If you turn that setting on, then you stop seeing the boosts and they're consumed immediately.

Sorry about the bad recording, but I think you can get the idea.. A single 5k, full greened both items. https://i.imgur.com/At5kKkY.mp4

**Comment by benway7000** [comment]
I didn't know about the auto-recycle setting; mine was off.  This means the recycled boosts should be appearing in my inventory.  I still have never seen that happen when an item is boosted, however I do see the recycled boosts appear when the infinity cube is boosted.  Was your first video above boosting the cube or other items?

If I turn on the auto-recycle option, it seems to be working as expected: sometimes I see my 10 boost adding 15 or 17 instead of just 10.   I don't see any reason why I would need the boosts to go in my inventory (just to be applied next pass) except for possibly when trying to max merge the boosts.  So I'm happy enough with this option enabled.

**Comment by benway7000** [comment]
I can still reproduce this with auto-recycle off:
1. disable Inventory Management while farming boosts
2. wait for several boosts in inventory of various types (I do not have conversion yet)
3. All of my gear has toughness maxed; therefore toughness boosts will be cubed but everything else will be applied to gear.
4. Re-enable Inventory Management
5. All speed & power boosts disappear (ie no recycling has occurred when they went into gear)
6. I see a few toughness boosts that are lower-tier than drop in the zone I was farming (cubed boosts are recycling).

I can try to make a video if you want to pursue this.

But since there is an easy workaround (turn on auto-recycle) and it's probably not that important in the grand scheme of things, I'm closing this. Thanks!
