### ISSUE TITLE
Bug: Iron Pill is not being bought automatically.

### ISSUE THREAD

**Issue by orcuttk** [rvazarkar/NGUInjector#73]
Even with more than sufficient blood, Injector is never buying Iron Pill right now.

**Comment by rvazarkar** [comment]
Are you specifying blood amount or stat amount for iron pill setting?

**Comment by orcuttk** [comment]
Interestingly, since you mentioned, I changed the number around and noticed it did not work when the number was low.  Double digits or less.  My goal was to just get it to "spend whatever blood it's got when off cooldown" so I had it set very low.

I have changed it to be 10,000 now and it is working again.
