### ISSUE TITLE
Problems with Boss Rebirth

### ISSUE THREAD

**Issue by Ruben0500** [rvazarkar/NGUInjector#74]
I have been trying to use the "Bosses" rebirth type, but it doesnt work right, it rebirth before the number of bosses I input, I'm doing it wrong or it's something in the code?.

Here is the input Im using:

 "Rebirth": {
    "Type": bosses,
    "Target": {
"10"
}
},

Also few examples of rebirth types could help a lot, Im trying to figure it out how this one works as with the numbers one too.

**Comment by rvazarkar** [comment]
```"Rebirth": {
    "Type": "Bosses",
    "Target": 5,
    "Challenges": []
  },```

**Comment by Ruben0500** [comment]
Now is working, Thanks for the help and for this amazing work you are doing for the NGU community
