### ISSUE TITLE
Suggestion: select Titan Level in Target Zone (or blacklist)

### ISSUE THREAD

**Issue by yoksi** [rvazarkar/NGUInjector#78]
hi, is it really not possible to choose the Titan version in the target zone or did I miss something?

right now if I want select higher level (after some AT) I must wait and not miss next respawn and select new Titan difficulty manually

"Blacklisted Enemies" in Adventure section not working also for specified Titan levels (tested on The Beast V1-3)

SUGGESTION II "FullAuto": what about add option for automatic change Titan Level based on actual P/T levels? ...after some AT you can fight Titan on higher level -right now you can change Level only manually

**Comment by L4Xi** [comment]
not so important, but point is that highest killable version of Titan can be different at start and in the middle of rebirth
