### ISSUE TITLE
Suggestion: Titans Fallthrough

### ISSUE THREAD

**Issue by yoksi** [rvazarkar/NGUInjector#80]
Even if you have stats for easily manual/idle kill Titan he is skipped because you cant autokill him yet.
A/T needed for autokill are much higher.
For example if you sniping higher zone then you must every hour kill Titan manually.

Maybe add Titans into fallthrough like regular Zones if you cant autokill them? some checkbox for that?

**Comment by L4Xi** [comment]
not so important and only unattended solution is select higher killable Titan in target zone and ITOPOD runs all the time
