### ISSUE TITLE
Suggestion: Allow "Auto Move to ITOPOD" to use Manual combat

### ISSUE THREAD

**Issue by masanbol** [rvazarkar/NGUInjector#88]
Currently the only way to use manual combat in ITOPOD is to select Combat Enabled on the Adventure tab and then select ITOPOD. This supersedes and prevents some tasks that use adventure mode, like manual questing via Auto Quest. Auto Quest, if enabled, even tees up a Major quest and sits on it at 0 as long as Adventure is enabled.

Since manual ITOPOD is more efficient than idle for generating PP (especially at high respawn in late game), it would be desirable to have this option. One way to accomplish this would be to make Auto Move to ITOPOD follow the settings for ITOPOD in the Adventure tab, whether Combat Enabled is selected or not.

Alternately, having all other tasks (Auto Quest, gold snipe, etc.) take priority over Adventure - Combat Enabled would also solve this issue.

**Comment by rvazarkar** [comment]
You seem to be running into some kind of weird behavior, because adventure is the lowest priority for anything right now. Everything takes priority over it, including questing and gold snipe. I've had that setup in place for a long time and its consistently behaved the way it should

**Comment by masanbol** [comment]
May have been a bug - I have had to restart the injector a few times. Just tested again and it looks like you're correct, so I will close this one.
