### ISSUE TITLE
ITOPOD constantly changing to tutorial zone after kill

### ISSUE THREAD

**Issue by cdmichaelb** [rvazarkar/NGUInjector#9]
I suspect it's this code here, I'm thinking that for some reason the zone isn't being reported right. Everything works fine in other zones.
`            //Move back to safe zone if we're in the wrong zone
            if (_character.adventure.zone != zone && _character.adventure.zone != -1)
            {
                MoveToZone(-1);
            }`

https://i.imgur.com/8LYDnaa.mp4
https://i.imgur.com/4XRbN1E.png

**Comment by cdmichaelb** [comment]
Upon reloading the game, and re-injecting the issue goes away. 

Have re-verified that on rebirth it breaks again. Seems to only happen after a rebirth.

**Comment by rvazarkar** [comment]
Its lazy shifter thats doing this, not the script

**Comment by cdmichaelb** [comment]
It's not, I just tested it.
