### ISSUE TITLE
Trying to add a fixed amount of energy to augs and time machine. 

### ISSUE THREAD

**Issue by matthewfarmery** [rvazarkar/NGUInjector#98]
Sorry if this is the wrong place to ask, But I''m really struggling trying to understand how to setup the injector script to pump so much energy into a certain augment and time machine. Everything I have tried, it either doesn't allocate the full amount, or it adds too much to one and not enough to another. 

Here is what I want. For the broken time machine, I only want the injector to add 200,000 energy. (especailly for 30 minute resets) then I want it to add the rest of the energy to milk infusion, (set to 100) then safety scissors. and about 20,000 for danger scissors. 

But from what I have done so far, it doesn't really work. I got it to fully max out the first ritual of blood magic, so I don't need to change anything there. But the energy thing is just driving me crazy. So I'm at a loss on what I'm doing wrong, or if the above simply isn't possible? I also tried using ":30" and see if it works in a percentage. but again, it doesn't seem to work correctly. 

Please help, or tell me what I'm doing wrong?

Thanks in advance.

**Comment by cdmichaelb** [comment]
Asking in here would be best: https://discord.gg/sGqKHyGSDb

It's a link to official NGU Discord #scripting channel.

**Comment by matthewfarmery** [comment]
I didn't see the script channel at first, will ask there. Thank you
